<?php declare(strict_types = 1);

//    $arrayOne = [
//        'foo' => 0,
//        'bar' => 1,
//        'baz' => 2,
//    ];
//
    $arrayTwo = [
        1 => 0,
        '2' => ['a','b'],
        2 => 1,
        3 => 2,
    ];

    $arrayThree = array(
        'foo' => 0,
        'bar' => 1,
        'baz' => 2,
    );

    $arrayFour = array(
        1 => 0,
        2 => 1,
        3 => 2,
    );
}
