language: php

php: 
 - 5.6

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
 - php vendor/sensiolabs/security-checker/security-checker security:check composer.lock
 - vendor/bin/phpcs --standard=psr2 src
 - vendor/bin/phpcs --standard=phpcs.xml src
 - vendor/bin/phpcs --standard=phpcs.xml tests --ignore=tests/Sniffs
 - vendor/bin/phpcs --standard=src/Codor/ruleset.xml src
 - vendor/bin/phpunit --debug --coverage-clover=coverage.xml
 - vendor/bin/phpmd src text codesize,unusedcode,naming
 - vendor/bin/phploc src --progress
 - vendor/bin/phpcpd src

after_success:
 - bash <(curl -s https://codecov.io/bash)
