<?php

// This looks like it has the word
// "and" but it's part of another word
function expand()
{

}

// This looks like it has the word
// "or" but it's part of another word
function orbit()
{

}

function thisDoesThisAndThat($foo)
{

	return "This and that";
}

function thisDoesThisOrThat($foo)
{
	return "This or that";
}

function this_and_that()
{

}

function that_And_This()
{

}

function this_or_that()
{

}

function that_Or_This()
{
	
}