<?php declare(strict_types = 1);

class foo
{
    public function bar()
    {
        $baz = 'baz';
    }

    /**
     * This is a doc block with many lines.
     * Foo
     * Bar
     * Baz
     * Lets fill up some more lines.
     * OK that should be good.
     * Well just one more...
     */
    public function thisHasALargeDocBlock()
    {
        $baz = 'baz';
    }

    /**
     * This is a doc block with many lines.
     * Foo
     * Bar
     * Baz
     * Lets fill up some more lines.
     * OK that should be good.
     * Well just one more...
     */
    public function another()
    {
        $baz = 'baz';
        $baz = 'baz';
        $baz = 'baz';
        // Some comments for fun
        // Some comments for fun
        // Some comments for fun
        // Some comments for fun
        // Some comments for fun
        // Some comments for fun
        $baz = 'baz';
        $baz = 'baz';
        $baz = 'baz';
    }

    /**
     * This is a doc block with many lines.
     * Foo
     * Bar
     * Baz
     * Lets fill up some more lines.
     * OK that should be good.
     * Well just one more...
     */
    public function yetAnother()
    {
        $baz = 'baz';
        $baz = 'baz';
        $baz = 'baz';
        // Some comments for fun
        // Some comments for fun
        // Some comments for fun
        // Some comments for fun
        // Some comments for fun
        // Some comments for fun
        $baz = 'baz';
        $baz = 'baz';
        $baz = 'baz';
    }











    /**
     * This is a doc block with many lines.
     * Foo
     * Bar
     * Baz
     * Lets fill up some more lines.
     * OK that should be good.
     * Well just one more...
     */
    public function portugal()
    {
        $baz = 'baz';
        $baz = 'baz';
        $baz = 'baz';
        // Some comments for fun
        // Some comments for fun
        // Some comments for fun
        // Some comments for fun
        // Some comments for fun
        // Some comments for fun
        $baz = 'baz';
        $baz = 'baz';
        $baz = 'baz';
    }
}