name: "Continuous Integration"

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  tests:
    name: "CI"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
        os:
          - ubuntu-latest
          - windows-latest
        composer:
          - "v2"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: composer:${{ matrix.composer }}

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress --prefer-dist"

      - name: "Run tests"
        run: "php vendor/bin/simple-phpunit --colors=always --testdox"
